- name: "[DELEGATE] Ensure node's hostname are binded to their VPN ipv4 address."
  lineinfile: >
    state=present dest=/etc/hosts
    regexp='^{{ item.ipv4 }}\s+'
    line='{{ item.ipv4 }} {{ item.hostname }}.vpn.local {{ item.hostname }}'
  when: proxmox_cluster_master
  delegate_to: "{{ item.external_ipv4 }}"
  with_items: proxmox_cluster_nodes
  tags:
    - proxmox_cluster_node

- name: "[DELEGATE] Ensure nodes have master's hostname binded"
  lineinfile: >
    state=present dest=/etc/hosts
    regexp='^{{ proxmox_cluster_internal_ipv4 }}\s+'
    line='{{ proxmox_cluster_internal_ipv4 }} {{ ansible_hostname }}.vpn.local {{ ansible_hostname }} pvelocalhost'
  when: proxmox_cluster_master
  delegate_to: "{{ item.external_ipv4 }}"
  with_items: proxmox_cluster_nodes
  tags:
    - proxmox_cluster_node


- name: "[DELEGATE] Ensure external ipv4 match only pvelocalhost"
  lineinfile: >
    state=present dest=/etc/hosts
    regexp='^{{ item.external_ipv4 }}\s+'
    line='{{ item.external_ipv4 }} {{ item.fqdn }}'
  delegate_to: "{{ item.external_ipv4 }}"
  with_items: proxmox_cluster_nodes
  tags:
    - proxmox_cluster_node
  when: proxmox_cluster_master
