---

- name: Configure dummies interfaces
  modprobe: name=dummy state=present params="numdummies=2"
  tags:
    - proxmox_cluster_master

- name: Ensure hostname is binded to VPN ipv4 address.
  lineinfile: >
    state=present dest=/etc/hosts
    regexp='^{{ proxmox_cluster_internal_ipv4 }}\s+'
    line='{{ proxmox_cluster_internal_ipv4 }} {{ ansible_hostname }}.vpn.local pvelocalhost {{ ansible_hostname }}'
  tags:
    - proxmox_cluster_master
  when: proxmox_cluster_master

- name: Ensure node's hostname are binded to their VPN ipv4 address.
  lineinfile: >
    state=present dest=/etc/hosts
    regexp='^{{ item.ipv4 }}\s+'
    line='{{ item.ipv4 }} {{ item.hostname }}.vpn.local {{ item.hostname }}'
  tags:
    - proxmox_cluster_master
  when: proxmox_cluster_master
  with_items: proxmox_cluster_nodes

- name: Ensure external ipv4 match only reverse hostname
  lineinfile: >
    state=present dest=/etc/hosts
    regexp='^{{ ansible_default_ipv4.address }}\s+'
    line='{{ ansible_default_ipv4.address }} {{ proxmox_cluster_master_fqdn }}'
  tags:
    - proxmox_cluster_master
  when: proxmox_cluster_master


