- name: ensure pve-enterprise repo is disable (need a valid subscription)
  file: path="/etc/apt/sources.list.d/pve-enterprise.list" state="absent"
  tags:
    - after-reboot

- name: Modprobe some modules to enable firewall in containers
  modprobe: name='{{ item }}'
  with_items: '{{ proxmox_modules }}'
  tags:
    - after-reboot

- name: Configure network interfaces (need reboot if changes)
  template:
    src:  "{{ proxmox_interfaces_template }}"
    dest: "{{ proxmox_interfaces_file }}"
  when: proxmox_interfaces_template | length

- name: Install proxmoxer and requests
  pip: name='{{ item }}'
  with_items: '{{ proxmox_pip_packages }}'
