- name: Check cluster status
  command: pvecm status
  changed_when: false
  ignore_errors: true
  register: cluster

- debug: var=cluster

- name: Create Cluster
  command: pvecm create {{ proxmox_cluster_name }}
  register: cluster_create
  when: cluster.stdout.find("Cluster Name:" ~ " " ~ proxmox_cluster_name ) == -1

- name: Check node status
  command: pvecm status
  delegate_to: "{{ item.external_ipv4}}"
  changed_when: false
  ignore_errors: true
  with_items: proxmox_cluster_nodes
  register: nodes

- debug: var=nodes

- name: Add node to cluster
  command: pvecm add {{ proxmox_cluster_internal_ipv4 }}
  delegate_to: "{{ item.item.external_ipv4 }}"
  register: add_nodes
  when: item.stdout.find("Cluster Name:" ~ " " ~ proxmox_cluster_name ) == -1
  with_items: nodes.results

- debug: var=add_nodes

- name: Configure 2nodes quorum | config_version
  xml: >
    file=/etc/pve/cluster.conf
    xpath=/cluster
    attribute=config_version
    value="{{ proxmox_cluster_conf.config_version }}"
  when: proxmox_cluster_conf | length >= 1
  notify: cluster restart

- name: Configure 2nodes quorum | two_nodes
  xml: >
    file=/etc/pve/cluster.conf
    xpath=/cluster/cman
    attribute=two_node
    value="{{ proxmox_cluster_conf.two_node }}"
  when: proxmox_cluster_conf | length >= 1

- name: Configure 2nodes quorum | expected_votes
  xml: >
    file=/etc/pve/cluster.conf
    xpath=/cluster/cman
    attribute=expected_votes
    value="{{ proxmox_cluster_conf.expected_votes }}"
  when: proxmox_cluster_conf | length >= 1
