---
# install proxmox VE (part 1)
#

- include: requirements.yml
  tags:
    - proxmox_install
    - proxmox_configure

- include: install.yml
  tags:
    - proxmox_install

- include: configure.yml
  tags:
    - proxmox_configure

- include: securize.yml
  tags:
    - proxmox_securize
  when: proxmox_restrict_webadmin | default(false)

- include: iscsi.yml
  tags:
    - proxmox_iscsi

- include: storage.yml
  tags:
    - proxmox_storage

- include: containers.yml
  tags:
    - proxmox_containers
