---
# Create openvz containers

- name: "create a vz container"
  pvectl: >
    command=create 
    ctid='{{ item.ctid }}'
    hostname='{{ item.hostname }}'
    password='{{ item.password }}'
    ip_address='{{ item.ip_address }}'
    memory='{{ item.memory }}'
    swap='{{ item.swap }}'
    ostemplate='{{ item.ostemplate }}'
    onboot='{{ item.onboot }}'
    cpus='{{ item.cpus }}'
    cpuunits='{{ item.cpuunits }}'
    disk='{{ item.disk }}'
  with_items: pve_containers
  register: ct_create
  failed_when: (ct_create.stderr is defined) and (ct_create.stderr.find('already exists') == -1 or (ct_create.stderr.find('failed') >= 0)
  tags:
    - openvz
